build: update verify release step

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -123,11 +123,12 @@ jobs:
           fetch-depth: 0
       - name: Verify release commit is tagged
         run: |
-          if ! git tag --points-at ${{ inputs.release_ref }}; then
-            echo '::error:: Release ref does not point to any tag. Please tag the merge commit of the release PR and try again'
+          tag=$(git tag --points-at ${{ inputs.release_ref }})
+          if [[ "$?" -ne 0 ]] || [[ -z "$tag" ]]; then
+            echo "::error:: Release ref does not point to any tag. Please tag the merge commit of the release PR and try again"
             exit 1
           else
-            echo 'Release commit verified'
+            echo "Release commit verified - $tag"
           fi
       - name: Configure git
         run: |
