feat: configure fork remote and create a new branch

diff --git a/.github/workflows/update_dependencies_pr.yml b/.github/workflows/update_dependencies_pr.yml
--- a/.github/workflows/update_dependencies_pr.yml
+++ b/.github/workflows/update_dependencies_pr.yml
@@ -38,7 +38,24 @@ jobs:
         with:
           repository: ${{ inputs.upstream_repository }}
           fetch-depth: 1
-      - uses: actions/setup-node@v6
+      - name: Configure git remote for the fork
+        # language=bash
+        run: |
+          ssh_url=$(gh repo view "${{ inputs.fork_repository }}" --json sshUrl --jq .sshUrl)
+          if [[ "$?" -ne 0 ]] || [[ -z "$ssh_url" ]]; then
+            echo "::error:: Cannot find the fork repository. Please make sure the fork_repository input points to the correct fork in the format of <repo_owner>/<repo_name>."
+            exit 1
+          fi
+          git remote add fork "$ssh_url"
+      - name: Create new branch
+        id: git_branch
+        # language=bash
+        run: |
+          branch_name="update-dependencies/$(date +%s)"
+          git checkout -b "$branch_name"
+          echo "BRANCH_NAME=$branch_name" >> "$GITHUB_OUTPUT"
+      - name: Setup Node
+        uses: actions/setup-node@v6
         with:
           node-version-file: .nvmrc
           cache: yarn
